defaultEntryPoints = ["http"]

# logLevel = "DEBUG"

[web]
  address = ":8088"
  [web.statistics]

[entryPoints]
[entryPoints.http]
address = ":80"

################################################################
# Docker configuration backend
################################################################
[docker]

endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true

# Expose containers by default in traefik
exposedbydefault = false

# Use Swarm Mode services as data provider
swarmmode = false

