# belbio secrets - added to config['secrets']

# Location of this file can be found in one of the following locations
#   first found is the one that is used
#   - ./belbio_secrets.yml    (just a regular file in the local directory or any parent directory)
#   - ~/.belbio_secrets       (a dotfile in the home directory)


bel_api:
    shared_secret: testme  # shared secret to validate JWT token
    servers:
        arangodb_password: ''


